### ISSUE TITLE
请问赚金豆分金豆现在有问题吗？我好像都是火爆了

### ISSUE THREAD

**Issue by aburdchen415** [lan-tianxiang/JS_TOOL#141]

**Comment by aburdchen415** [comment]
❗️赚京豆, 错误!
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at /root/jd/scripts/jd_syj.js:716:59
    at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/root/jd/scripts/jd_syj.js:845:4869)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by aburdchen415** [comment]
】助力
助力结果：未知错误
{"message":"活动太火爆，请稍后再试","officialDocument":"活动太火爆，请稍后再试","resultCode":"2400201","resultTips":"活动太火爆，请稍后再试","success":false}

**Comment by lan-tianxiang** [comment]
脚本没问题，提示太火爆应该是次数用完了，你看一下0点的记录
