### ISSUE TITLE
控制面板无法打开 127.0.0.0.1 拒绝访问，已打防火墙

### ISSUE THREAD

**Issue by cjli1234** [lan-tianxiang/JS_TOOL#165]
~/jd/panel$ node server.js
/home/tea/jd/panel/node_modules/got/dist/source/create.js:157
    const paginateEach = (async function* (url, options) {
                                        ^

SyntaxError: Unexpected token *
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/tea/jd/panel/node_modules/got/dist/source/index.js:14:18)

**Comment by cjli1234** [comment]
Status: active

To                         Action      From
--                         ------      ----
5678                       ALLOW       Anywhere
5678/tcp                   ALLOW       Anywhere
Anywhere                   ALLOW       192.168.3.247
5678 (v6)                  ALLOW       Anywhere (v6)
5678/tcp (v6)              ALLOW       Anywhere (v6)

**Comment by cjli1234** [comment]
~/jd$ bash jd.sh panelon
记得开启前先认真看Wiki中，功能页里关于控制面板的事项

确认看过WIKI，打开浏览器，地址为你的127.0.0.1:5678

您的操作系统为：Debian 架构：x86_64

**Comment by CACAVOK** [comment]
我是WSL，用的`localhost:5678`可以正常使用
