### ISSUE TITLE
省钱大赢家之翻翻乐 报错

### ISSUE THREAD

**Issue by zdmisif** [lan-tianxiang/JS_TOOL#201]
查询下次翻翻乐剩余时间失败：{"msg":"data does not exist","code":12,"success":false}

❗️省钱大赢家之翻翻乐, 错误!
TypeError: Cannot read property 'helpResult' of undefined
    at /home/pi/jd/scripts/jd_big_winner.js:352:31
    at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/home/pi/jd/scripts/jd_big_winner.js:593:4791)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by moxinshi** [comment]
这个活动结束了吧

**Comment by zdmisif** [comment]
> 这个活动结束了吧

这样纸
