### ISSUE TITLE
执行 jd_summer_movement脚本出错，谢谢

### ISSUE THREAD

**Issue by LvDeShei** [lan-tianxiang/JS_TOOL#266]
🔔燃动夏季, 开始!
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'fs/promises'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/root/jd/scripts/MovementFaker.js:2:12)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
您的操作系统为：Centos 架构：x86_64

**Comment by oopuuu** [comment]
+1同样的错误

**Comment by lan-tianxiang** [comment]
更新一下再试试

**Comment by oopuuu** [comment]
> 更新一下再试试

更新以后仍旧一样的错误

🔔燃动夏季, 开始!
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'fs/promises'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/root/JS_TOOL/scripts/MovementFaker.js:2:12)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
您的操作系统为：Centos 架构：x86_64

**Comment by lan-tianxiang** [comment]
好的，修复了！！
