### ISSUE TITLE
燃动夏季jd_summer_movement，运行出错！

### ISSUE THREAD

**Issue by LvDeShei** [lan-tianxiang/JS_TOOL#300]
昨天（07-09）手动执行 jd jd_summer_movement.js now 还可以，没出问题，今天早上（07-10）就不行了

*****开始【京东账号2】abc*****

如有未完成的任务，请多执行几次

待兑换金额：7.36 当前等级:1  111990/250000(攒卡领5元)

运动
MovementFaker: 95.109ms

❗️燃动夏季, 错误!
TypeError: Cannot read property 'get_risk_result' of undefined
    at MovementFaker.run (/root/jd/scripts/MovementFaker.js:28:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
{"code":"1","echo":"required string parameter 'functionId' is not present"}
TypeError: Cannot read property 'init' of undefined
    at MovementFaker.init (/root/jd/scripts/MovementFaker.js:72:24)

❗️燃动夏季, 错误!
TypeError: Cannot read property 'get_risk_result' of undefined
    at MovementFaker.run (/root/jd/scripts/MovementFaker.js:28:28)
{"code":"1","echo":"required string parameter 'functionId' is not present"}
MovementFaker: 78.509ms

**Comment by lan-tianxiang** [comment]
好的

**Comment by lan-tianxiang** [comment]
已修复
